"""Test claims generated by code (not by a model) to probe a drafted rule.

Starting from a few varied synthetic base claims, the generator changes exactly
the fields the drafted spec reads, towards the edges where rules usually go
wrong: missing or blank values, values just below / at / just above every
number the rule compares against, boundary dates, other known and unknown
codes, duplicated or removed list entries. Every case must still pass the claim
schema and transport checks, because the rule engine never sees anything else.
"""

from __future__ import annotations

import copy
import json
from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Any, Callable

from normalisation.schema_subset import validate as validate_claim_schema
from rule_engine.catalogue import DATE, NUMBER, TEXT, FieldCatalogue, ReferenceData
from rule_engine.engine_core import validate_transport
from rule_engine.language import ConfigValue, DaysBetweenValue, LiteralValue, Node, RuleSpec
from rule_engine.validation import analyse_spec

DEFAULT_LIMIT = 40
LIST_FIELDS = ("/lines", "/authorizations", "/attachments")


@dataclass
class EdgeCase:
    case_id: str
    description: str
    claim: dict[str, Any]


@dataclass
class LabelledCase:
    """A test claim whose correct outcome the rule's author has confirmed."""

    description: str
    claim: dict[str, Any]
    expected_status: str

    def to_json(self) -> dict[str, Any]:
        return {"description": self.description, "claim": self.claim, "expected_status": self.expected_status}

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> "LabelledCase":
        return cls(description=data["description"], claim=data["claim"], expected_status=data["expected_status"])


@dataclass
class _Hints:
    """What the spec itself says about interesting values."""

    numbers: set = field(default_factory=set)
    texts: set = field(default_factory=set)
    dates: set = field(default_factory=set)
    policy_fields: set = field(default_factory=set)
    uses_day_counts: bool = False

    @classmethod
    def from_spec(cls, spec: RuleSpec) -> "_Hints":
        hints = cls()
        for node in _walk(spec):
            if isinstance(node, LiteralValue):
                literal = node.value
                if isinstance(literal, bool):
                    continue
                if isinstance(literal, (int, float)):
                    hints.numbers.add(literal)
                elif _parse_date(literal):
                    hints.dates.add(literal)
                elif literal:
                    hints.texts.add(literal)
            elif isinstance(node, ConfigValue) and node.config == "policy" and node.get:
                if isinstance(node.get[0], str):
                    hints.policy_fields.add(node.get[0])
            elif isinstance(node, DaysBetweenValue):
                hints.uses_day_counts = True
        return hints


Mutation = tuple[str, Callable[[dict[str, Any]], None]]


class EdgeCaseGenerator:
    def __init__(
        self,
        base_claims: list[dict[str, Any]],
        fields: FieldCatalogue,
        reference: ReferenceData,
        claim_schema: dict[str, Any],
        limit: int = DEFAULT_LIMIT,
    ):
        self.base_claims = base_claims
        self.fields = fields
        self.reference = reference
        self.claim_schema = claim_schema
        self.limit = limit

    def generate(self, spec: RuleSpec) -> list[EdgeCase]:
        fields_read = sorted(analyse_spec(spec, self.fields).fields_read)
        hints = _Hints.from_spec(spec)

        groups: dict[str, list[tuple[dict, Mutation]]] = {}
        for label, base in zip("ABCDEF", self.base_claims):
            for path in fields_read:
                for mutation in self._mutations(path, base, label, fields_read, hints):
                    groups.setdefault(path, []).append((base, mutation))

        cases: list[EdgeCase] = []
        seen: set[str] = set()

        def add(description: str, claim: dict[str, Any]) -> None:
            key = json.dumps(claim, sort_keys=True)
            if key in seen or not self._is_valid(claim):
                return
            seen.add(key)
            cases.append(EdgeCase(case_id=f"c{len(cases) + 1}", description=description, claim=claim))

        for label, base in zip("ABCDEF", self.base_claims):
            add(f"claim {label} unchanged", copy.deepcopy(base))

        # Round-robin over the fields so every field the rule reads gets probed.
        while groups and len(cases) < self.limit:
            for path in list(groups):
                if not groups[path]:
                    del groups[path]
                    continue
                base, (description, mutate) = groups[path].pop(0)
                claim = copy.deepcopy(base)
                mutate(claim)
                add(description, claim)
                if len(cases) >= self.limit:
                    break
        return cases

    # --------------------------------------------------------------- mutations

    def _mutations(self, path, base, label, fields_read, hints) -> list[Mutation]:
        if path in LIST_FIELDS:
            return self._list_mutations(path, base, label)
        info = self.fields.get(path)
        located = _locate(base, path)
        if info is None or located is None:
            return []
        container, key, shown = located
        current = container[key]
        mutations = []
        for value, why in self._candidates(path, info, current, base, fields_read, hints):
            if value == current and why != "unchanged":
                continue
            description = f"claim {label}: {shown} = {json.dumps(value)} ({why}; was {json.dumps(current)})"
            mutations.append((description, _setter(path, value)))
        return mutations

    def _candidates(self, path, info, current, base, fields_read, hints):
        candidates: list[tuple[Any, str]] = []
        if info.nullable:
            candidates.append((None, "missing"))
        if TEXT in info.types:
            candidates.append(("", "blank"))
            candidates.extend((text, "value named in the rule") for text in sorted(hints.texts))
            candidates.extend((text.lower(), "different letter case") for text in sorted(hints.texts) if text.lower() != text)
            candidates.extend(self._domain_values(path, base))
        if NUMBER in info.types:
            for number in sorted(hints.numbers | self._policy_numbers(base, hints)):
                candidates.extend(_around(number))
            candidates.append((0, "zero"))
            candidates.append((-1, "negative"))
            if isinstance(current, (int, float)) and not isinstance(current, bool):
                candidates.append((round(current + 0.01, 2), "one cent more"))
                candidates.append((current * 2, "doubled"))
        if DATE in info.types:
            for literal in sorted(hints.dates):
                candidates.extend(_shift_all(literal, "date named in the rule"))
            for other in fields_read:
                if other != path and DATE in getattr(self.fields.get(other), "types", ()):
                    located = _locate(base, other)
                    other_value = located[0][located[1]] if located else None
                    if _parse_date(other_value):
                        candidates.extend(_shift_all(other_value, f"relative to {other}"))
                        if hints.uses_day_counts:
                            for days in sorted(self._policy_numbers(base, hints)):
                                if isinstance(days, int) and 0 < days < 3650:
                                    candidates.extend(_shift_all(_add_days(other_value, days), f"{days} days after {other}"))
            if _parse_date(current):
                candidates.extend(_shift_all(current, "current date"))
        return candidates[:14]

    def _domain_values(self, path: str, base: dict[str, Any]) -> list[tuple[Any, str]]:
        name = path.rsplit("/", 1)[-1]
        policy = self.reference.policies.get(base.get("policy_id"), {})
        if name == "service_code":
            special = sorted(set(policy.get("auth_required_services", [])) | set(policy.get("required_documents", {})))
            ordinary = [code for code in sorted(self.reference.services) if code not in special]
            return [(code, "known service code") for code in (special[:2] + ordinary[:1])] + [("SVC-UNKNOWN", "unknown service code")]
        if name == "provider_id":
            allowed = policy.get("allowed_providers", [])
            others = [pid for pid in self.reference.provider_ids if pid not in allowed]
            return [(pid, "allowed provider") for pid in allowed[:1]] + [(pid, "known provider not allowed by the policy") for pid in others[:1]] + [("EDU-PROV-UNKNOWN", "unknown provider")]
        if name == "policy_id":
            return [(pid, "other policy") for pid in sorted(self.reference.policies) if pid != base.get("policy_id")] + [("EDU-UNKNOWN-POLICY", "unknown policy")]
        if name == "diagnosis_code":
            return [(code, "known diagnosis") for code in self.reference.diagnosis_codes[:2]] + [("DX-UNKNOWN", "unknown diagnosis")]
        if name == "currency":
            return [("USD", "other currency")]
        return []

    def _policy_numbers(self, base: dict[str, Any], hints: _Hints) -> set:
        """Numbers from the claim's policy fields that the rule reads (e.g. price limits)."""
        policy = self.reference.policies.get(base.get("policy_id"), {})
        codes = {line.get("service_code") for line in base.get("lines", [])}
        numbers = set()
        for name in hints.policy_fields:
            value = policy.get(name)
            if isinstance(value, (int, float)) and not isinstance(value, bool):
                numbers.add(value)
            elif isinstance(value, dict):
                numbers.update(v for code, v in value.items() if code in codes and isinstance(v, (int, float)))
        return numbers

    def _list_mutations(self, path: str, base: dict[str, Any], label: str) -> list[Mutation]:
        name = path.strip("/")
        items = base.get(name) or []
        mutations: list[Mutation] = []
        if items:
            def duplicate(claim, name=name):
                twin = copy.deepcopy(claim[name][0])
                if name == "lines":
                    twin["line_id"] = f"{twin['line_id']}-DUP"
                claim[name].append(twin)
            mutations.append((f"claim {label}: first entry of {name} duplicated", duplicate))
        if name != "lines" and items:
            mutations.append((f"claim {label}: {name} emptied", lambda claim, name=name: claim.__setitem__(name, [])))
        return mutations

    def _is_valid(self, claim: dict[str, Any]) -> bool:
        try:
            validate_claim_schema(claim, self.claim_schema)
            validate_transport(claim)
        except (ValueError, KeyError, TypeError):
            return False
        return True


def choose_base_claims(claims: list[dict[str, Any]], count: int = 3) -> list[dict[str, Any]]:
    """Pick varied base claims deterministically, so edge cases have context to work with."""
    criteria = [
        # authorizations and documents, for rules about them
        lambda claim, chosen: bool(claim["authorizations"]) and bool(claim["attachments"]),
        # several lines and no authorizations, for line-level and duplicate rules
        lambda claim, chosen: len(claim["lines"]) > 1 and not claim["authorizations"],
        # a policy not used yet, for policy-dependent rules
        lambda claim, chosen: all(claim["policy_id"] != other["policy_id"] for other in chosen),
    ]
    chosen: list[dict[str, Any]] = []
    for matches in criteria:
        match = next((claim for claim in claims if claim not in chosen and matches(claim, chosen)), None)
        if match is not None:
            chosen.append(match)
    for claim in claims:
        if len(chosen) >= count:
            break
        if claim not in chosen:
            chosen.append(claim)
    return chosen[:count]


# ------------------------------------------------------------------ helpers


def _walk(node: Node):
    pending = [node]
    while pending:
        current = pending.pop()
        yield current
        for name in type(current).model_fields:
            child = getattr(current, name)
            children = child if isinstance(child, list) else [child]
            pending.extend(item for item in children if isinstance(item, Node))


def _locate(claim: dict[str, Any], path: str):
    """Container, key and a readable label for a catalogue path (first list element)."""
    container: Any = claim
    parts = path.strip("/").split("/")
    shown: list[str] = []
    for index, part in enumerate(parts):
        last = index == len(parts) - 1
        if part == "*":
            if not isinstance(container, list) or not container:
                return None
            container = container[0]
            shown[-1] += "[0]"
            continue
        if not isinstance(container, dict) or part not in container:
            return None
        shown.append(part)
        if last:
            return container, part, ".".join(shown)
        container = container[part]
    return None


def _setter(path: str, value: Any) -> Callable[[dict[str, Any]], None]:
    def mutate(claim: dict[str, Any]) -> None:
        located = _locate(claim, path)
        if located is not None:
            container, key, _ = located
            container[key] = value
    return mutate


def _around(number) -> list[tuple[Any, str]]:
    step = 1 if isinstance(number, int) else 0.01
    return [
        (round(number - step, 2), f"just below {number}"),
        (number, f"exactly {number}"),
        (round(number + step, 2), f"just above {number}"),
    ]


def _parse_date(value: Any) -> date | None:
    if not isinstance(value, str) or len(value) != 10:
        return None
    try:
        return date.fromisoformat(value)
    except ValueError:
        return None


def _add_days(value: str, days: int) -> str:
    return (date.fromisoformat(value) + timedelta(days=days)).isoformat()


def _shift_all(value: str, why: str) -> list[tuple[str, str]]:
    return [
        (_add_days(value, -1), f"one day before ({why})"),
        (value, f"same day ({why})"),
        (_add_days(value, 1), f"one day after ({why})"),
    ]
